Yorku\JuturnaBundle\Entity\Logo:
    type: entity
    table: logos
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        imagename:
            type: string
            length: 255
            nullable: true
            column: imagename
        imageFilename:
            type: string
            length: 255
            nullable: true
            column: image_filename
        imagePath:
            type: string
            length: 255
            nullable: true
            column: image_path
        description:
            type: text
            nullable: true
            column: description
        websiteUrl:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: website_url
        imageTip:
            type: string
            length: 125
            fixed: false
            nullable: true
            column: image_tip
        enabled:
            type: boolean
            nullable: true
            column: enabled
        showSeq:
            type: integer
            unsigned: false
            nullable: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    lifecycleCallbacks: {  }
